"""
PlatformIO pre-build script: fetches root CA certs for Anthropic endpoints
and writes firmware/src/anthropic_ca.h before compilation.

Strategy per host:
  - Walk the TLS chain served by the endpoint.
  - If the last cert is self-signed, use it as the trust anchor.
  - Otherwise follow its AIA CA-Issuers URL (HTTP DER) to get the real root.
  - Deduplicate by SHA-256 fingerprint.
  - Write all unique roots to anthropic_ca.h as a concatenated PEM bundle.

Falls back to the existing file if the network is unreachable.
Requires: openssl CLI.
"""
import subprocess
import re
import os
import urllib.request
from datetime import datetime, timezone

Import("env")  # noqa: F821  (SCons injection)

HOSTS = ["api.anthropic.com", "console.anthropic.com"]

OUT = os.path.join(env.subst("$PROJECT_SRC_DIR"), "anthropic_ca.h")  # noqa: F821


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _run(args, stdin=None, timeout=10):
    return subprocess.run(
        args, input=stdin,
        stdout=subprocess.PIPE, stderr=subprocess.PIPE,
        timeout=timeout,
    )


def pem_blocks(text):
    return [m.strip() for m in re.findall(
        r"-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----",
        text, re.DOTALL)]


def cert_text(pem):
    return _run(["openssl", "x509", "-noout", "-text"],
                stdin=pem.encode()).stdout.decode()


def cert_field(pem, *flags):
    return _run(["openssl", "x509", "-noout"] + list(flags),
                stdin=pem.encode()).stdout.decode().strip()


def sha256_fp(pem):
    return _run(["openssl", "x509", "-noout", "-fingerprint", "-sha256"],
                stdin=pem.encode()).stdout.decode().strip()


def is_self_signed(pem):
    r = _run(["openssl", "x509", "-noout", "-subject_hash", "-issuer_hash"],
             stdin=pem.encode())
    lines = r.stdout.decode().strip().splitlines()
    return len(lines) == 2 and lines[0] == lines[1]


def aia_url(pem):
    m = re.search(r"CA Issuers.*?URI:(http[^\s]+)", cert_text(pem))
    return m.group(1) if m else None


def der_url_to_pem(url):
    with urllib.request.urlopen(url, timeout=10) as resp:
        der = resp.read()
    r = _run(["openssl", "x509", "-inform", "DER", "-outform", "PEM"], stdin=der)
    return r.stdout.decode().strip()


def fetch_chain(host):
    r = _run(["openssl", "s_client", "-connect", f"{host}:443", "-showcerts"],
             stdin=b"")
    return pem_blocks(r.stdout.decode("utf-8", errors="ignore"))


def resolve_root(host):
    """Return the root CA PEM for the given host."""
    chain = fetch_chain(host)
    if not chain:
        raise RuntimeError("empty chain")
    last = chain[-1]
    if is_self_signed(last):
        return last
    # Follow AIA to find the root CA the server did not send.
    url = aia_url(last)
    if not url:
        raise RuntimeError(f"no AIA CA Issuers URL in last cert for {host}")
    print(f"fetch_ca: {host}: following AIA {url}")
    root = der_url_to_pem(url)
    if not root:
        raise RuntimeError(f"failed to fetch/convert DER from {url}")
    return root


# ---------------------------------------------------------------------------
# Pre-build action
# ---------------------------------------------------------------------------

def regenerate(target, source, env_):  # noqa: ARG001
    seen = {}  # fingerprint -> (host, pem)
    errors = []

    for host in HOSTS:
        try:
            pem = resolve_root(host)
            fp = sha256_fp(pem)
            if fp not in seen:
                seen[fp] = (host, pem)
                subj = cert_field(pem, "-subject")
                print(f"fetch_ca: {host}: {subj} [{fp}]")
            else:
                print(f"fetch_ca: {host}: same root as {seen[fp][0]}, skipping")
        except Exception as exc:
            errors.append(f"{host}: {exc}")
            print(f"fetch_ca: WARNING: {host}: {exc}")

    if not seen:
        print("fetch_ca: WARNING: no certs fetched - keeping existing anthropic_ca.h")
        return
    if errors:
        print(f"fetch_ca: WARNING: {len(errors)} host(s) failed; partial bundle written")

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines = [
        "#pragma once",
        "",
        "// TLS root CA bundle for Anthropic endpoints.",
        "// Auto-generated by firmware/tools/fetch_ca.py -- do not edit by hand.",
        "// mbedTLS (ESP-IDF) accepts concatenated PEM; all certs below are loaded.",
        "//",
        "// Endpoints covered:",
    ]
    for fp, (host, pem) in seen.items():
        subj = cert_field(pem, "-subject")
        end  = cert_field(pem, "-enddate")
        lines.append(f"//   {host}  ->  {subj}  ({end})")
    lines += [
        f"// Generated: {now}",
        "//",
        "// To refresh: rebuild with network access.",
        "",
        'static const char ANTHROPIC_ROOT_CA[] PROGMEM = R"EOF(',
    ]
    for fp, (host, pem) in seen.items():
        subj = cert_field(pem, "-subject")
        lines.append(f"// {host} - {subj}")
        lines.append(pem)
        lines.append("")
    lines += [')EOF";', ""]

    with open(OUT, "w") as f:
        f.write("\n".join(lines))

    print(f"fetch_ca: wrote {len(seen)} root CA cert(s) -> {OUT}")


# Run immediately at script-load time so it always executes even on cached builds.
regenerate(None, None, env)
